import React,{useCallback,useState}from"react";
import{View,Text,StyleSheet,FlatList,Pressable,TextInput,Modal,ScrollView,Alert,Platform}from"react-native";
import{useFocusEffect,useRouter}from"expo-router";
import{SafeAreaView}from"react-native-safe-area-context";
import{MaterialCommunityIcons}from"@expo/vector-icons";
import{Image}from"expo-image";
import{adminApi}from"@/src/roleApi";
import{COLORS,RADIUS,SPACING}from"@/src/theme";
import ImageUploader from"@/src/components/ImageUploader";

const EMPTY={name:"",category:"",vendor_name:"",location:"Patna",price:"",unit:"visit",rating:"4.8",reviews:"0",icon:"tools",description:"",image:"",tag:"",order:"99",active:true};
const UNITS=["visit","day","hour"];

export default function AdminDailyServices(){
 const router=useRouter(); const[items,setItems]=useState<any[]>([]); const[bookings,setBookings]=useState<any[]>([]); const[stats,setStats]=useState<any>({}); const[modal,setModal]=useState(false); const[editing,setEditing]=useState<any>(null); const[f,setF]=useState<any>({...EMPTY});
 const load=useCallback(async()=>{try{const[a,b,c]=await Promise.all([adminApi.vendorServices(),adminApi.serviceBookings(),adminApi.dailyServiceStats()]);setItems((a||[]).filter((x:any)=>x.service_type==="daily_service"));setBookings((b||[]).filter((x:any)=>x.service_type==="daily_service"));setStats(c||{})}catch(e){console.log("daily admin",e)}},[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 const open=(x?:any)=>{setEditing(x||null);setF(x?{...EMPTY,...x,price:String(x.price??""),rating:String(x.rating??"4.8"),reviews:String(x.reviews??"0"),order:String(x.order??99)}:{...EMPTY});setModal(true)};
 const save=async()=>{if(!f.name.trim()||!f.category.trim()){const msg="Service name and category are required";Platform.OS==="web"?window.alert(msg):Alert.alert("Required",msg);return}const data={...f,name:f.name.trim(),price:Number(f.price)||0,rating:Number(f.rating)||0,reviews:Number(f.reviews)||0,order:Number(f.order)||99,service_type:"daily_service",active:true};try{if(editing)await adminApi.updateVendorService(editing.id,data);else await adminApi.createVendorService(data);setModal(false);await load();Platform.OS==="web"?window.alert("Daily Service saved and live"):Alert.alert("Saved","Daily Service saved and live")}catch(e:any){Platform.OS==="web"?window.alert(e?.message||"Save failed"):Alert.alert("Save failed",e?.message||"Save failed")}};
 const remove=async(id:string)=>{if(Platform.OS==="web"&&!window.confirm("Delete this service?"))return;await adminApi.deleteVendorService(id);load()};
 return <SafeAreaView style={s.root} edges={["top"]}>
  <View style={s.header}><Pressable onPress={()=>router.back()}><MaterialCommunityIcons name="arrow-left" size={24}/></Pressable><View style={{flex:1,alignItems:"center"}}><Text style={s.title}>Daily Services Admin</Text><Text style={s.sub}>User panel management</Text></View><Pressable onPress={()=>open()}><MaterialCommunityIcons name="plus-circle" size={28} color="#0284C7"/></Pressable></View>
  <FlatList data={items} keyExtractor={x=>x.id} contentContainerStyle={{padding:14,paddingBottom:60}} ListHeaderComponent={<>
   <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:9,paddingBottom:12}}>
    <KPI icon="tools" label="Services" value={stats.services??items.length}/><KPI icon="check-circle" label="Active" value={stats.active_services??0}/><KPI icon="calendar-check" label="Bookings" value={stats.bookings??bookings.length}/><KPI icon="cash-multiple" label="Revenue" value={`₹${Number(stats.revenue||0).toLocaleString("en-IN")}`}/><KPI icon="wallet" label="Earnings" value={`₹${Number(stats.platform_earnings||0).toLocaleString("en-IN")}`}/>
   </ScrollView>
   <View style={s.section}><Text style={s.sectionTitle}>Manage User Panel</Text><Text style={s.sectionSub}>These services and fields are shown directly to customers.</Text></View>
  </>} renderItem={({item})=><View style={s.card}>
   {item.image?<Image source={{uri:item.image}} style={s.img} contentFit="cover"/>:<View style={[s.img,s.ph]}><MaterialCommunityIcons name={item.icon||"tools"} size={30} color="#0284C7"/></View>}
   <View style={{flex:1,padding:12}}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{item.name}</Text><Text style={s.vendor}>{item.vendor_name||"KMT Bazaar Home Services"}</Text></View><View style={s.live}><View style={s.dot}/><Text style={s.liveText}>LIVE</Text></View></View>
   <Text style={s.meta}>{item.category} · {item.location||"Patna"}</Text><Text style={s.meta}>{item.rating||0} ★ · {item.reviews||0} reviews</Text><Text style={s.price}>₹{Number(item.price||0).toLocaleString("en-IN")} / {item.unit||"visit"}</Text><Text style={s.desc} numberOfLines={2}>{item.description}</Text>
   <View style={s.actions}><Pressable onPress={()=>open(item)} style={s.edit}><MaterialCommunityIcons name="pencil-outline" size={17} color="#0284C7"/><Text style={s.editText}>Edit & Go Live</Text></Pressable><Pressable onPress={async()=>{await adminApi.deleteVendorService(item.id);load()}}><MaterialCommunityIcons name="trash-can-outline" size={20} color="#DC2626"/></Pressable></View></View>
  </View>}
  ListFooterComponent={<View style={s.bookings}><Text style={s.sectionTitle}>Recent Daily Service Bookings</Text>{bookings.slice(0,8).map((b:any)=><View key={b.id} style={s.booking}><View style={{flex:1}}><Text style={s.name}>{b.service_name||"Daily Service"}</Text><Text style={s.meta}>{b.customer_name||"Customer"} · {b.booking_date||"Date not set"}</Text></View><Text style={s.status}>{String(b.status||"pending").toUpperCase()}</Text></View>)}</View>}
  />
  <Modal visible={modal} transparent animationType="slide" onRequestClose={()=>setModal(false)}><View style={m.back}><View style={m.sheet}><ScrollView showsVerticalScrollIndicator keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingBottom:30}}>
   <View style={m.head}><View><Text style={m.title}>{editing?"Edit Daily Service":"Add Daily Service"}</Text><Text style={m.help}>Changes save directly to the customer panel.</Text></View><Pressable onPress={()=>setModal(false)}><MaterialCommunityIcons name="close" size={24}/></Pressable></View>
   <Field l="Service Name *" v={f.name} c={(v:string)=>setF({...f,name:v})} p="Plumber"/><Field l="Category *" v={f.category} c={(v:string)=>setF({...f,category:v})} p="Plumbing"/><Field l="Service Provider Name" v={f.vendor_name} c={(v:string)=>setF({...f,vendor_name:v})} p="KMT Home Experts"/><Field l="Location" v={f.location} c={(v:string)=>setF({...f,location:v})} p="Patna"/>
   <View style={m.two}><Field l="Price" v={f.price} c={(v:string)=>setF({...f,price:v})} p="399" k="numeric"/><Field l="Rating" v={f.rating} c={(v:string)=>setF({...f,rating:v})} p="4.8" k="numeric"/></View>
   <View style={m.two}><Field l="Reviews" v={f.reviews} c={(v:string)=>setF({...f,reviews:v})} p="182" k="numeric"/><Field l="Sort Order" v={f.order} c={(v:string)=>setF({...f,order:v})} p="1" k="numeric"/></View>
   <Text style={m.label}>Unit</Text><View style={m.chips}>{UNITS.map(x=><Pressable key={x} onPress={()=>setF({...f,unit:x})} style={[m.chip,f.unit===x&&m.active]}><Text style={[m.chipText,f.unit===x&&m.activeText]}>{x}</Text></Pressable>)}</View>
   <Field l="Icon" v={f.icon} c={(v:string)=>setF({...f,icon:v})} p="tools"/><Field l="Tag" v={f.tag} c={(v:string)=>setF({...f,tag:v})} p="Popular"/><Field l="Description" v={f.description} c={(v:string)=>setF({...f,description:v})} p="Tap repair, leakage..." multi/>
   <ImageUploader value={f.image} onChange={(uri)=>setF({...f,image:uri})} label="Service Photo" aspect={[16,9]}/>
   <View style={m.buttons}><Pressable onPress={()=>setModal(false)} style={[m.btn,m.cancel]}><Text>Cancel</Text></Pressable><Pressable onPress={save} style={[m.btn,m.save]}><Text style={{color:"#fff",fontWeight:"900"}}>{editing?"Save & Go Live":"Add & Go Live"}</Text></Pressable></View>
  </ScrollView></View></View></Modal>
 </SafeAreaView>
}
function Field({l,v,c,p,k,multi}:any){return <View style={{marginBottom:9,flex:1}}><Text style={m.label}>{l}</Text><TextInput value={String(v??"")} onChangeText={c} placeholder={p} keyboardType={k} multiline={multi} style={[m.input,multi&&{minHeight:70,textAlignVertical:"top"}]}/></View>}
function KPI({icon,label,value}:any){return <View style={s.kpi}><MaterialCommunityIcons name={icon} size={18} color="#0284C7"/><Text style={s.kpiVal}>{value}</Text><Text style={s.kpiLabel}>{label}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#F6F9FC"},header:{flexDirection:"row",alignItems:"center",padding:15,backgroundColor:"#fff",borderBottomWidth:1,borderColor:"#E2E8F0"},title:{fontSize:19,fontWeight:"900"},sub:{fontSize:10,color:"#64748B"},kpi:{minWidth:105,padding:12,borderRadius:15,backgroundColor:"#fff",borderWidth:1,borderColor:"#E2E8F0"},kpiVal:{fontSize:17,fontWeight:"900",marginTop:5},kpiLabel:{fontSize:10,color:"#64748B"},section:{paddingVertical:8},sectionTitle:{fontSize:17,fontWeight:"900"},sectionSub:{fontSize:11,color:"#64748B",marginTop:3},card:{backgroundColor:"#fff",borderRadius:17,marginBottom:12,borderWidth:1,borderColor:"#E2E8F0",overflow:"hidden"},img:{height:150,width:"100%"},ph:{alignItems:"center",justifyContent:"center",backgroundColor:"#E0F2FE"},row:{flexDirection:"row",alignItems:"center"},name:{fontSize:16,fontWeight:"900"},vendor:{fontSize:11,color:"#0284C7",marginTop:3},meta:{fontSize:11,color:"#64748B",marginTop:4},price:{fontSize:18,fontWeight:"900",marginTop:8},desc:{fontSize:11,color:"#64748B",marginTop:5},live:{flexDirection:"row",alignItems:"center",gap:4},dot:{width:7,height:7,borderRadius:4,backgroundColor:"#22C55E"},liveText:{fontSize:9,fontWeight:"900",color:"#15803D"},actions:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:12},edit:{flexDirection:"row",alignItems:"center",gap:6},editText:{fontWeight:"900",color:"#0284C7"},bookings:{marginTop:16,paddingTop:8},booking:{backgroundColor:"#fff",padding:12,borderRadius:12,borderWidth:1,borderColor:"#E2E8F0",marginTop:7,flexDirection:"row",alignItems:"center"},status:{fontSize:9,fontWeight:"900",color:"#0284C7"}});
const m=StyleSheet.create({back:{flex:1,backgroundColor:"rgba(0,0,0,.55)",justifyContent:"flex-end"},sheet:{backgroundColor:"#fff",maxHeight:"94%",borderTopLeftRadius:24,borderTopRightRadius:24,padding:18},head:{flexDirection:"row",justifyContent:"space-between",marginBottom:12},title:{fontSize:20,fontWeight:"900"},help:{fontSize:11,color:"#64748B",marginTop:3},label:{fontSize:11,fontWeight:"900",color:"#475569",marginBottom:4},input:{backgroundColor:"#F8FAFC",borderWidth:1,borderColor:"#E2E8F0",borderRadius:11,padding:11},two:{flexDirection:"row",gap:9},chips:{flexDirection:"row",gap:7,marginBottom:10},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:20,borderWidth:1,borderColor:"#E2E8F0"},active:{backgroundColor:"#0284C7",borderColor:"#0284C7"},chipText:{fontWeight:"800",color:"#475569"},activeText:{color:"#fff"},buttons:{flexDirection:"row",gap:9,marginTop:12},btn:{flex:1,padding:13,borderRadius:12,alignItems:"center"},cancel:{borderWidth:1,borderColor:"#E2E8F0"},save:{backgroundColor:"#0284C7"}});
