import React, { useEffect, useState } from "react";
import { View, Text, StyleSheet, Pressable, ActivityIndicator, ScrollView } from "react-native";
import { useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { api } from "@/src/api";
import { COLORS, RADIUS, SPACING } from "@/src/theme";

export default function TravelCheckout(){
 const router=useRouter(); const [cart,setCart]=useState<any>(null); const [addresses,setAddresses]=useState<any[]>([]); const [addressId,setAddressId]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{Promise.all([api.travelCart(),api.addresses()]).then(([c,a])=>{setCart(c);setAddresses(a||[]);if(a?.[0])setAddressId(a[0].id)}).catch(()=>{})},[]);
 const book=async()=>{if(!addressId||!cart?.items?.length)return;setBusy(true);try{const b=await api.travelCheckout({address_id:addressId,payment_method:"cod",notes:"Travel booking from KMT Bazaar"});router.replace({pathname:"/orders/[id]",params:{id:b.id}} as any)}finally{setBusy(false)}};
 if(!cart)return <SafeAreaView style={s.center}><ActivityIndicator size="large" color={COLORS.brand}/></SafeAreaView>;
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={{padding:SPACING.lg}}><Text style={s.title}>Confirm Your Trip</Text><View style={s.summary}><Text style={s.heading}>{cart.items.length} travel package(s)</Text><Text style={s.total}>₹{Number(cart.total||0).toLocaleString("en-IN")}</Text></View><Text style={s.section}>Booking contact / address</Text>{addresses.length?addresses.map(a=><Pressable key={a.id} onPress={()=>setAddressId(a.id)} style={[s.address,addressId===a.id&&s.selected]}><MaterialCommunityIcons name={addressId===a.id?"radiobox-marked":"radiobox-blank"} size={22} color={COLORS.brand}/><View style={{flex:1}}><Text style={s.addrName}>{a.full_name}</Text><Text style={s.addr}>{a.line1}, {a.city}, {a.state} - {a.pincode}</Text></View></Pressable>):<Text style={s.noAddress}>Please add an address before booking.</Text>}</ScrollView><View style={s.bottom}><Pressable disabled={busy||!addressId} onPress={book} style={[s.cta,(!addressId)&&{opacity:.5}]}>{busy?<ActivityIndicator color="#fff"/>:<><Text style={s.ctaText}>Confirm Booking · ₹{Number(cart.total||0).toLocaleString("en-IN")}</Text><MaterialCommunityIcons name="check" size={20} color="#fff"/></>}</Pressable></View></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#F8FAFC"},center:{flex:1,alignItems:"center",justifyContent:"center"},title:{fontSize:25,fontWeight:"900",color:COLORS.text,marginBottom:18},summary:{backgroundColor:"#E0F2FE",padding:18,borderRadius:16,flexDirection:"row",justifyContent:"space-between",alignItems:"center"},heading:{fontWeight:"800",color:COLORS.text},total:{fontSize:20,fontWeight:"900",color:COLORS.text},section:{fontSize:18,fontWeight:"900",color:COLORS.text,marginTop:25,marginBottom:10},address:{backgroundColor:"#fff",padding:14,borderRadius:14,marginBottom:10,flexDirection:"row",alignItems:"center",gap:10,borderWidth:1,borderColor:COLORS.border},selected:{borderColor:COLORS.brand,backgroundColor:"#F0F9FF"},addrName:{fontWeight:"800",color:COLORS.text},addr:{fontSize:12,color:COLORS.textSecondary,marginTop:3},noAddress:{color:COLORS.textMuted},bottom:{position:"absolute",left:0,right:0,bottom:0,padding:12,backgroundColor:"#fff",borderTopWidth:1,borderColor:COLORS.border},cta:{backgroundColor:COLORS.accent,paddingVertical:15,borderRadius:RADIUS.pill,alignItems:"center",justifyContent:"center",flexDirection:"row",gap:8},ctaText:{color:"#fff",fontWeight:"900",fontSize:14}});
