import React, { useEffect, useState } from "react";
import { View, Text, StyleSheet, ScrollView, Pressable, TextInput, ActivityIndicator } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { SafeAreaView } from "react-native-safe-area-context";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import { adminApi } from "@/src/roleApi";
import { api } from "@/src/api";
import { COLORS, RADIUS, SPACING } from "@/src/theme";

export default function AdminBannerPage(){
 const {id}=useLocalSearchParams<{id:string}>();const router=useRouter();const [loading,setLoading]=useState(true);const [page,setPage]=useState<any>({});const [packages,setPackages]=useState<any[]>([]);const [saving,setSaving]=useState(false);
 useEffect(()=>{if(!id)return;api.bannerPage(String(id)).then(d=>{setPage(d.page||{});setPackages(d.packages||[])}).finally(()=>setLoading(false))},[id]);
 const save=async()=>{setSaving(true);try{await adminApi.updateBannerPage(String(id),page);alert("Page saved")}finally{setSaving(false)}};
 const addPackage=async()=>{const p=await adminApi.createTravelPackage(String(id),{banner_id:String(id),title:"New Holiday Package",destination:"",duration:"",price:0,child_price:0,hotel:"",flight:"",flight_image:"",images:[],description:"",inclusions:[]});setPackages(x=>[...x,p])};
 if(loading)return <SafeAreaView style={s.center}><ActivityIndicator size="large" color={COLORS.brand}/></SafeAreaView>;
 return <SafeAreaView style={s.root}><View style={s.header}><Pressable onPress={()=>router.back()}><MaterialCommunityIcons name="arrow-left" size={23} color={COLORS.text}/></Pressable><Text style={s.title}>Customize Travel Page</Text><Pressable onPress={save} disabled={saving}><Text style={s.save}>{saving?"...":"SAVE"}</Text></Pressable></View><ScrollView contentContainerStyle={{padding:SPACING.lg}}>
 <Text style={s.section}>Page Design</Text>
 <Input label="Brand name" value={page.brand_name} onChange={(v:any)=>setPage({...page,brand_name:v})}/><Input label="Hero title" value={page.hero_title} onChange={(v:any)=>setPage({...page,hero_title:v})}/><Input label="Hero subtitle" value={page.hero_subtitle} onChange={(v:any)=>setPage({...page,hero_subtitle:v})}/><Input label="Hero image URL" value={page.hero_image} onChange={(v:any)=>setPage({...page,hero_image:v})}/><Input label="Description" value={page.description} onChange={(v:any)=>setPage({...page,description:v})}/>
 <Text style={s.section}>Animations</Text><View style={s.animRow}><Toggle label="Flying plane" value={page.animation_plane!==false} onChange={(v:any)=>setPage({...page,animation_plane:v})}/><Toggle label="Moving clouds" value={page.animation_clouds!==false} onChange={(v:any)=>setPage({...page,animation_clouds:v})}/><Toggle label="Parallax" value={page.animation_parallax!==false} onChange={(v:any)=>setPage({...page,animation_parallax:v})}/></View>
 <View style={s.packageHead}><Text style={s.section}>Holiday Packages</Text><Pressable onPress={addPackage} style={s.add}><MaterialCommunityIcons name="plus" size={18} color="#fff"/><Text style={s.addText}>Add</Text></Pressable></View>
 {packages.map((p:any)=><PackageEditor key={p.id} pkg={p} bannerId={String(id)} onDelete={()=>setPackages(x=>x.filter(a=>a.id!==p.id))}/>)}
 </ScrollView></SafeAreaView>
}
function Input({label,value,onChange}:any){return <View><Text style={s.label}>{label}</Text><TextInput value={String(value||"")} onChangeText={onChange} placeholder={label} placeholderTextColor={COLORS.textMuted} style={s.input}/></View>}
function Toggle({label,value,onChange}:any){return <Pressable onPress={()=>onChange(!value)} style={s.toggle}><MaterialCommunityIcons name={value?"checkbox-marked":"checkbox-blank-outline"} size={22} color={value?COLORS.brand:COLORS.textMuted}/><Text style={s.toggleText}>{label}</Text></Pressable>}
function PackageEditor({pkg,bannerId,onDelete}:any){const [p,setP]=useState(pkg);const [saving,setSaving]=useState(false);const save=async()=>{setSaving(true);try{await adminApi.updateTravelPackage(bannerId,p.id,p)}finally{setSaving(false)}};return <View style={s.package}><Text style={s.packageTitle}>{p.title||"Package"}</Text><Input label="Package title" value={p.title} onChange={(v:any)=>setP({...p,title:v})}/><Input label="Destination" value={p.destination} onChange={(v:any)=>setP({...p,destination:v})}/><Input label="Duration" value={p.duration} onChange={(v:any)=>setP({...p,duration:v})}/><Input label="Adult price" value={p.price} onChange={(v:any)=>setP({...p,price:Number(v)||0})}/><Input label="Child price" value={p.child_price} onChange={(v:any)=>setP({...p,child_price:Number(v)||0})}/><Input label="Hotel" value={p.hotel} onChange={(v:any)=>setP({...p,hotel:v})}/><Input label="Flight / transport" value={p.flight} onChange={(v:any)=>setP({...p,flight:v})}/><Input label="Main image URL" value={p.images?.[0]} onChange={(v:any)=>setP({...p,images:[v,...(p.images||[]).slice(1)]})}/><View style={s.actions}><Pressable onPress={save} style={s.small}><Text style={s.smallText}>{saving?"Saving...":"Save Package"}</Text></Pressable><Pressable onPress={async()=>{await adminApi.deleteTravelPackage(bannerId,p.id);onDelete()}} style={[s.small,{backgroundColor:"#DC2626"}]}><Text style={s.smallText}>Delete</Text></Pressable></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#F8FAFC"},center:{flex:1,alignItems:"center",justifyContent:"center"},header:{height:58,backgroundColor:"#fff",flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:SPACING.lg,borderBottomWidth:1,borderColor:COLORS.border},title:{fontSize:17,fontWeight:"900",color:COLORS.text},save:{color:COLORS.brand,fontWeight:"900"},section:{fontSize:20,fontWeight:"900",color:COLORS.text,marginTop:6,marginBottom:10},label:{fontSize:11,fontWeight:"800",color:COLORS.textMuted,marginTop:8,marginBottom:4},input:{backgroundColor:"#fff",borderWidth:1,borderColor:COLORS.border,borderRadius:10,padding:11,color:COLORS.text},animRow:{backgroundColor:"#fff",borderRadius:14,padding:10,borderWidth:1,borderColor:COLORS.border},toggle:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:7},toggleText:{fontWeight:"700",color:COLORS.text},packageHead:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:20},add:{backgroundColor:COLORS.brand,paddingHorizontal:13,paddingVertical:8,borderRadius:RADIUS.pill,flexDirection:"row",alignItems:"center",gap:4},addText:{color:"#fff",fontWeight:"800"},package:{backgroundColor:"#fff",borderRadius:16,padding:14,marginBottom:14,borderWidth:1,borderColor:COLORS.border},packageTitle:{fontSize:16,fontWeight:"900",color:COLORS.text},actions:{flexDirection:"row",gap:8,marginTop:12},small:{backgroundColor:COLORS.accent,paddingHorizontal:15,paddingVertical:10,borderRadius:RADIUS.pill},smallText:{color:"#fff",fontWeight:"800"}});
