import React,{useEffect,useMemo,useState}from"react";
import{View,Text,StyleSheet,ScrollView,Pressable,TextInput,ActivityIndicator,Platform,Alert}from"react-native";
import{Image}from"expo-image";
import{LinearGradient}from"expo-linear-gradient";
import{MaterialCommunityIcons}from"@expo/vector-icons";
import{useLocalSearchParams,useRouter}from"expo-router";
import{SafeAreaView}from"react-native-safe-area-context";
import{api}from"@/src/api";

const RED="#ef233c",BLACK="#08090b",CARD="#111318",MUTED="#a6abb4",WHITE="#fff",LINE="#242833";
const MOCK=[
{id:"mock-car-innova",name:"Toyota Innova Crysta",location:"Patna",price:3200,seats:7,image:"https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=1200&q=85",category:"With Driver",vendor_name:"KMT Tours & Travel"},
{id:"mock-car-ertiga",name:"Maruti Ertiga",location:"Gaya",price:2400,seats:6,image:"https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=1200&q=85",category:"Tour & Travel",vendor_name:"Bihar Road Trips"},
{id:"mock-car-dzire",name:"Maruti Dzire",location:"Patna",price:1600,seats:4,image:"https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=1200&q=85",category:"Airport & City",vendor_name:"CityRide Bihar"},
{id:"mock-car-fortuner",name:"Toyota Fortuner",location:"Ranchi",price:5200,seats:7,image:"https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=1200&q=85",category:"Premium",vendor_name:"Elite Roadways"},
{id:"mock-car-tempo",name:"Tempo Traveller 12 Seater",location:"Varanasi",price:6800,seats:12,image:"https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=1200&q=85",category:"Group Tour",vendor_name:"India Group Travels"},
{id:"mock-car-self-drive",name:"Hyundai Creta Self Drive",location:"Patna",price:2900,seats:5,image:"https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=1200&q=85",category:"Self Drive",vendor_name:"DriveEasy Rentals"}];

export default function CarTripBuilder(){
 const r=useRouter(),{carId}=useLocalSearchParams<{carId:string}>();
 const [car,setCar]=useState<any>(null),[loading,setLoading]=useState(true);
 const [pickup,setPickup]=useState(""),[dropoff,setDropoff]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState("09:00"),[days,setDays]=useState(1),[passengers,setPassengers]=useState(2),[note,setNote]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const d=await api.serviceCatalog("car_rental");const all=Array.isArray(d)?d:[];const found=all.find((x:any)=>x.id===carId);setCar(found||MOCK.find(x=>x.id===carId)||MOCK[0])}catch{setCar(MOCK.find(x=>x.id===carId)||MOCK[0])}finally{setLoading(false)}})()},[carId]);
 const total=useMemo(()=>Number(car?.price||0)*days,[car,days]);
 const next=async()=>{
  if(!car)return;
  if(!pickup.trim()||!date.trim()){const m="Please enter pickup location and travel date.";Platform.OS==="web"?window.alert(m):Alert.alert("Trip details required",m);return}
  try{setBusy(true);await api.serviceCartAdd({service_type:"car_rental",service_id:car.id,booking_date:date.trim(),booking_time:time||"09:00",quantity:days,notes:note.trim(),extra:{passengers,rental_days:days,pickup_location:pickup.trim(),dropoff_location:dropoff.trim(),package_name:car.name,destination:car.location||"India",package_price:Number(car.price||0),duration:days+" day"+(days>1?"s":""),vendor_name:car.vendor_name||"KMT Bazaar Car Rentals",source:String(car.id).startsWith("mock-")?"mock-car":"vendor-service"}});r.push("/service-booking-cart" as any)}catch(e:any){const m=e?.message||"Could not start booking.";Platform.OS==="web"?window.alert(m):Alert.alert("Car booking",m)}finally{setBusy(false)}
 };
 if(loading||!car)return <SafeAreaView style={s.root}><View style={s.center}><ActivityIndicator color={RED} size="large"/></View></SafeAreaView>;
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.page} showsVerticalScrollIndicator={false}>
 <LinearGradient colors={["#050608","#17090d","#08090b"]} style={s.hero}><View style={s.back}><Pressable onPress={()=>r.back()} style={s.backBtn}><MaterialCommunityIcons name="arrow-left" size={21} color={WHITE}/></Pressable><View><Text style={s.eyebrow}>KMT BAZAAR · CAR RENTAL</Text><Text style={s.heroTitle}>Trip Builder</Text></View></View><View style={s.heroLine}/><Text style={s.heroSub}>Plan your route, choose your travel details and continue directly to booking contact.</Text></LinearGradient>
 <View style={s.wrap}>
 <View style={s.carCard}><Image source={{uri:car.image}} style={s.carImg} contentFit="cover"/><View style={{flex:1,padding:13}}><Text style={s.carName}>{car.name}</Text><Text style={s.carMeta}>{car.location} · {car.category}</Text><Text style={s.vendor}>{car.vendor_name}</Text><Text style={s.carPrice}>₹{Number(car.price||0).toLocaleString("en-IN")} <Text style={s.per}>/ day</Text></Text></View></View>
 <View style={s.card}><Text style={s.label}>YOUR ROUTE</Text><Text style={s.fieldLabel}>PICKUP LOCATION *</Text><TextInput value={pickup} onChangeText={setPickup} placeholder="e.g. Patna Airport" placeholderTextColor="#777d87" style={s.input}/>
 <Text style={s.fieldLabel}>DROP / DESTINATION</Text><TextInput value={dropoff} onChangeText={setDropoff} placeholder="e.g. Bodh Gaya / Varanasi" placeholderTextColor="#777d87" style={s.input}/>
 <View style={s.row}><View style={{flex:1}}><Text style={s.fieldLabel}>TRAVEL DATE *</Text><TextInput value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" placeholderTextColor="#777d87" style={s.input}/></View><View style={{flex:1}}><Text style={s.fieldLabel}>PICKUP TIME</Text><TextInput value={time} onChangeText={setTime} placeholder="09:00" placeholderTextColor="#777d87" style={s.input}/></View></View>
 <View style={s.row}><Counter title="RENTAL DAYS" value={days} min={1} max={30} onChange={setDays}/><Counter title="PASSENGERS" value={passengers} min={1} max={Number(car.seats||7)} onChange={setPassengers}/></View>
 <Text style={s.fieldLabel}>TRIP NOTES</Text><TextInput value={note} onChangeText={setNote} placeholder="Sightseeing, airport timing, special request..." placeholderTextColor="#777d87" multiline style={[s.input,s.note]}/>
 </View>
 <View style={s.total}><View><Text style={s.totalSmall}>{days} day{days>1?"s":""} × ₹{Number(car.price||0).toLocaleString("en-IN")}</Text><Text style={s.totalTitle}>Estimated trip total</Text></View><Text style={s.totalPrice}>₹{total.toLocaleString("en-IN")}</Text></View>
 <Pressable disabled={busy} onPress={next} style={s.next}>{busy?<ActivityIndicator color="#fff"/>:<><Text style={s.nextText}>Continue to Booking Contact</Text><MaterialCommunityIcons name="arrow-right" size={21} color={WHITE}/></>}</Pressable>
 <Text style={s.noteText}>Next: name + mobile → checkout → payment → booking confirmation.</Text>
 </View></ScrollView></SafeAreaView>
}
function Counter({title,value,min,max,onChange}:{title:string,value:number,min:number,max:number,onChange:(n:number)=>void}){return <View style={{flex:1}}><Text style={s.fieldLabel}>{title}</Text><View style={s.counter}><Pressable onPress={()=>onChange(Math.max(min,value-1))} style={s.cbtn}><Text style={s.ct}>−</Text></Pressable><Text style={s.cv}>{value}</Text><Pressable onPress={()=>onChange(Math.min(max,value+1))} style={s.cbtn}><Text style={s.ct}>+</Text></Pressable></View></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:BLACK},page:{paddingBottom:60},hero:{padding:18,paddingTop:18,paddingBottom:25},back:{flexDirection:"row",alignItems:"center",gap:13},backBtn:{width:40,height:40,borderRadius:12,backgroundColor:"#1b1e24",alignItems:"center",justifyContent:"center"},eyebrow:{fontSize:10,fontWeight:"900",letterSpacing:1.6,color:RED},heroTitle:{fontSize:31,fontWeight:"900",color:WHITE,marginTop:3},heroLine:{height:2,width:70,backgroundColor:RED,marginTop:18,borderRadius:2},heroSub:{color:"#b7bbc3",fontSize:13,lineHeight:20,marginTop:12,maxWidth:700},wrap:{maxWidth:800,width:"calc(100% - 28px)" as any,alignSelf:"center"},carCard:{marginTop:14,flexDirection:"row",backgroundColor:CARD,borderRadius:18,overflow:"hidden",borderWidth:1,borderColor:LINE},carImg:{width:145,height:120},carName:{color:WHITE,fontSize:18,fontWeight:"900"},carMeta:{color:"#b7bbc3",fontSize:11,marginTop:5},vendor:{color:"#777e89",fontSize:10,marginTop:5},carPrice:{color:RED,fontSize:18,fontWeight:"900",marginTop:9},per:{color:MUTED,fontSize:10},card:{marginTop:14,padding:17,borderRadius:19,backgroundColor:CARD,borderWidth:1,borderColor:LINE},label:{color:RED,fontSize:11,fontWeight:"900",letterSpacing:1.5,marginBottom:13},fieldLabel:{color:"#9ca1aa",fontSize:9,fontWeight:"900",letterSpacing:1,marginBottom:7,marginTop:5},input:{backgroundColor:"#171a20",borderWidth:1,borderColor:"#2b3039",borderRadius:12,padding:13,color:WHITE,fontSize:14,marginBottom:10},row:{flexDirection:"row",gap:10},note:{minHeight:80,textAlignVertical:"top" as any},counter:{height:48,backgroundColor:"#171a20",borderWidth:1,borderColor:"#2b3039",borderRadius:12,flexDirection:"row",alignItems:"center",justifyContent:"space-between",padding:6,marginBottom:10},cbtn:{width:36,height:36,borderRadius:10,backgroundColor:"#282d36",alignItems:"center",justifyContent:"center"},ct:{color:WHITE,fontSize:21},cv:{color:WHITE,fontWeight:"900",fontSize:16},total:{marginTop:13,padding:16,borderRadius:17,backgroundColor:"#28090e",borderWidth:1,borderColor:"rgba(239,35,60,.35)",flexDirection:"row",alignItems:"center",justifyContent:"space-between"},totalSmall:{color:"#ffb9c1",fontSize:11},totalTitle:{color:WHITE,fontSize:15,fontWeight:"900",marginTop:3},totalPrice:{color:WHITE,fontSize:23,fontWeight:"900"},next:{marginTop:11,borderRadius:14,padding:16,backgroundColor:RED,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},nextText:{color:WHITE,fontSize:15,fontWeight:"900"},noteText:{color:"#666c76",fontSize:10,textAlign:"center",marginTop:9},center:{flex:1,alignItems:"center",justifyContent:"center"}});
