import React,{useEffect,useState}from"react";
import{View,Text,StyleSheet,ScrollView,Pressable,TextInput,Alert,Platform,ActivityIndicator}from"react-native";
import{useLocalSearchParams,useRouter}from"expo-router";
import{SafeAreaView}from"react-native-safe-area-context";
import{MaterialCommunityIcons}from"@expo/vector-icons";
import{Image}from"expo-image";
import{api}from"@/src/api";

const MOCK:any[]=[
{id:"mock-daily-plumber",name:"Plumber",category:"Plumbing",vendor_name:"KMT Home Experts",location:"Patna",price:399,unit:"visit",rating:4.8,image:"https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=1200&q=85"},
{id:"mock-daily-electrician",name:"Electrician",category:"Electrical",vendor_name:"PowerFix Services",location:"Patna",price:349,unit:"visit",rating:4.9,image:"https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=1200&q=85"},
{id:"mock-daily-ac",name:"AC Technician",category:"AC Service",vendor_name:"CoolCare Experts",location:"Patna",price:499,unit:"visit",rating:4.8,image:"https://images.unsplash.com/photo-1631545806609-4e9dce9c2c4e?w=1200&q=85"},
{id:"mock-daily-mistri",name:"Mistri / Mason",category:"Masonry",vendor_name:"BuildRight Works",location:"Patna",price:799,unit:"day",rating:4.7,image:"https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1200&q=85"},
{id:"mock-daily-labour",name:"Daily Labour",category:"Labour",vendor_name:"KMT Labour Network",location:"Patna",price:699,unit:"day",rating:4.6,image:"https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=85"},
{id:"mock-daily-carpenter",name:"Carpenter",category:"Carpentry",vendor_name:"WoodCraft Services",location:"Patna",price:449,unit:"visit",rating:4.8,image:"https://images.unsplash.com/photo-1504148455328-c376907d081c?w=1200&q=85"},
{id:"mock-daily-painter",name:"Painter",category:"Painting",vendor_name:"ColorPro Team",location:"Patna",price:899,unit:"day",rating:4.7,image:"https://images.unsplash.com/photo-1562259949-90c4265a7c9f?w=1200&q=85"},
{id:"mock-daily-cleaner",name:"Home Cleaner",category:"Cleaning",vendor_name:"Sparkle Home Care",location:"Patna",price:499,unit:"visit",rating:4.8,image:"https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1200&q=85"}
];

export default function DailyServiceBooking(){
const router=useRouter(),{serviceId}=useLocalSearchParams<any>(),[item,setItem]=useState<any>(null),[loading,setLoading]=useState(true),[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState("10:00"),[address,setAddress]=useState(""),[note,setNote]=useState(""),[plan,setPlan]=useState<"booking"|"full">("booking"),[busy,setBusy]=useState(false);
useEffect(()=>{(async()=>{try{const live=await api.serviceCatalog("daily_service");const found=Array.isArray(live)?live.find((x:any)=>x.id===serviceId):null;setItem(found||MOCK.find(x=>x.id===serviceId)||MOCK[0])}catch{setItem(MOCK.find(x=>x.id===serviceId)||MOCK[0])}finally{setLoading(false)}})()},[serviceId]);
const total=Number(item?.price||0),advance=Math.round(total*.2),pay=plan==="full"?total:advance;
const fail=(title:string,msg:string)=>{if(Platform.OS==="web")window.alert(msg);else Alert.alert(title,msg)};
const submit=async()=>{if(!item)return;if(name.trim().length<2)return fail("Name required","Please enter your full name.");if(phone.replace(/\D/g,"").length!==10)return fail("Mobile required","Please enter a valid 10-digit mobile number.");if(!date.trim())return fail("Date required","Please enter the service date.");if(!address.trim())return fail("Address required","Please enter the service address.");try{setBusy(true);await api.serviceCartAdd({service_type:"daily_service",service_id:item.id,booking_date:date.trim(),booking_time:time.trim(),quantity:1,notes:note.trim(),extra:{package_name:item.name,package_price:total,destination:item.location||"Patna",vendor_name:item.vendor_name||"KMT Bazaar Services",service_category:item.category||"",customer_name:name.trim(),customer_phone:phone.replace(/\D/g,""),customer_email:email.trim(),service_address:address.trim(),source:String(item.id).startsWith("mock-")?"mock-daily":"vendor-service"}});await api.serviceCartCustomer({full_name:name.trim(),phone:phone.replace(/\D/g,""),email:email.trim()});router.push({pathname:"/service-payment" as any,params:{plan,amount:String(pay),total:String(total),flow:"daily"}} as any)}catch(e:any){fail("Booking",e?.message||"Could not create booking.")}finally{setBusy(false)}};
if(loading)return <SafeAreaView style={s.root}><ActivityIndicator size="large" color="#0284c7" style={{marginTop:80}}/></SafeAreaView>;
return <SafeAreaView style={s.root}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.page}><Pressable onPress={()=>router.back()} style={s.back}><MaterialCommunityIcons name="arrow-left" size={22} color="#0f172a"/><Text style={s.backText}>Daily Services</Text></Pressable>
<View style={s.heroCard}><Image source={{uri:item?.image}} style={s.heroImage} contentFit="cover"/><View style={s.heroBody}><Text style={s.category}>{item?.category}</Text><Text style={s.title}>{item?.name}</Text><Text style={s.vendor}>{item?.vendor_name} · {item?.location}</Text><View style={s.heroBottom}><View><Text style={s.from}>Starting from</Text><Text style={s.price}>₹{total.toLocaleString("en-IN")} <Text style={s.per}>/{item?.unit||"visit"}</Text></Text></View><View style={s.rating}><MaterialCommunityIcons name="star" size={14} color="#f59e0b"/><Text style={s.ratingText}>{item?.rating||4.8}</Text></View></View></View></View>
<Text style={s.section}>Booking details</Text><Text style={s.helper}>Tell us who is booking, when the professional should visit and where.</Text>
<Field label="FULL NAME *" value={name} onChangeText={setName} placeholder="Your full name"/><Field label="MOBILE NUMBER *" value={phone} onChangeText={v=>setPhone(v.replace(/\D/g,""))} placeholder="10-digit mobile number" keyboardType="phone-pad" maxLength={10}/><Field label="EMAIL (OPTIONAL)" value={email} onChangeText={setEmail} placeholder="Email for confirmation" keyboardType="email-address"/><Field label="SERVICE DATE *" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" maxLength={10}/><Field label="PREFERRED TIME" value={time} onChangeText={setTime} placeholder="e.g. 10:00"/><Field label="SERVICE ADDRESS *" value={address} onChangeText={setAddress} placeholder="House no., street, area, city" multiline height={82}/><Field label="WORK / PROBLEM DETAILS" value={note} onChangeText={setNote} placeholder="Tell the professional what needs to be done" multiline height={92}/>
<Text style={s.section}>Choose payment</Text>
<Pressable onPress={()=>setPlan("booking")} style={[s.payOption,plan==="booking"&&s.payActive]}><View style={s.radio}>{plan==="booking"&&<View style={s.radioIn}/>}</View><View style={{flex:1}}><Text style={s.payTitle}>Pay booking amount</Text><Text style={s.paySub}>20% now · remaining later</Text></View><Text style={s.payAmt}>₹{advance.toLocaleString("en-IN")}</Text></Pressable>
<Pressable onPress={()=>setPlan("full")} style={[s.payOption,plan==="full"&&s.payActive]}><View style={s.radio}>{plan==="full"&&<View style={s.radioIn}/>}</View><View style={{flex:1}}><Text style={s.payTitle}>Pay full amount</Text><Text style={s.paySub}>Complete payment now</Text></View><Text style={s.payAmt}>₹{total.toLocaleString("en-IN")}</Text></Pressable>
<View style={s.totalBox}><Text style={s.totalLabel}>Pay now</Text><Text style={s.total}>₹{pay.toLocaleString("en-IN")}</Text></View>
<Pressable disabled={busy} onPress={submit} style={s.btn}>{busy?<ActivityIndicator color="#fff"/>:<><Text style={s.btnText}>Continue to Payment</Text><MaterialCommunityIcons name="arrow-right" size={20} color="#fff"/></>}</Pressable><Text style={s.note}>Payment uses KMT Bazaar's current test gateway. The booking is created after successful payment.</Text>
</ScrollView></SafeAreaView>
}
function Field({label,value,onChangeText,placeholder,multiline=false,height=52,keyboardType="default",maxLength}:{label:string,value:string,onChangeText:(v:string)=>void,placeholder:string,multiline?:boolean,height?:number,keyboardType?:any,maxLength?:number}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#94a3b8" multiline={multiline} keyboardType={keyboardType} maxLength={maxLength} style={[s.input,multiline&&{height,textAlignVertical:"top"}]}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f6f9fc"},page:{padding:16,paddingBottom:40,maxWidth:760,width:"100%",alignSelf:"center"},back:{flexDirection:"row",alignItems:"center",gap:8,paddingVertical:7},backText:{fontWeight:"800",color:"#334155"},heroCard:{backgroundColor:"#fff",borderRadius:22,overflow:"hidden",borderWidth:1,borderColor:"#e2e8f0",marginTop:9},heroImage:{width:"100%",height:190},heroBody:{padding:17},category:{fontSize:10,fontWeight:"900",letterSpacing:1.2,color:"#0284c7"},title:{fontSize:26,fontWeight:"900",color:"#0f172a",marginTop:4},vendor:{fontSize:12,color:"#64748b",marginTop:4},heroBottom:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-end",marginTop:15},from:{fontSize:10,color:"#94a3b8"},price:{fontSize:23,fontWeight:"900",color:"#0f172a",marginTop:2},per:{fontSize:11,color:"#64748b"},rating:{flexDirection:"row",alignItems:"center",gap:3,paddingHorizontal:9,paddingVertical:6,backgroundColor:"#fff7ed",borderRadius:10},ratingText:{fontSize:11,fontWeight:"900",color:"#9a3412"},section:{fontSize:20,fontWeight:"900",color:"#0f172a",marginTop:22},helper:{fontSize:12,color:"#64748b",lineHeight:18,marginTop:4,marginBottom:10},field:{marginTop:12},label:{fontSize:10,fontWeight:"900",letterSpacing:1.1,color:"#475569",marginBottom:6},input:{backgroundColor:"#fff",borderWidth:1,borderColor:"#dbe4ee",borderRadius:13,paddingHorizontal:13,paddingVertical:12,fontSize:14,color:"#0f172a",minHeight:52},payOption:{flexDirection:"row",alignItems:"center",gap:11,padding:14,borderRadius:15,borderWidth:1,borderColor:"#dbe4ee",backgroundColor:"#fff",marginTop:9},payActive:{borderColor:"#0284c7",backgroundColor:"#effaff"},radio:{width:21,height:21,borderRadius:11,borderWidth:2,borderColor:"#0284c7",alignItems:"center",justifyContent:"center"},radioIn:{width:11,height:11,borderRadius:6,backgroundColor:"#0284c7"},payTitle:{fontSize:14,fontWeight:"900",color:"#0f172a"},paySub:{fontSize:11,color:"#64748b",marginTop:2},payAmt:{fontSize:16,fontWeight:"900",color:"#ea580c"},totalBox:{marginTop:14,padding:17,borderRadius:16,backgroundColor:"#071827",flexDirection:"row",justifyContent:"space-between",alignItems:"center"},totalLabel:{color:"#b8c9d7",fontWeight:"700"},total:{color:"#fff",fontSize:24,fontWeight:"900"},btn:{marginTop:12,backgroundColor:"#0284c7",padding:16,borderRadius:15,flexDirection:"row",justifyContent:"center",alignItems:"center",gap:8},btnText:{color:"#fff",fontSize:16,fontWeight:"900"},note:{fontSize:10,color:"#94a3b8",textAlign:"center",lineHeight:16,marginTop:10}
});