import React,{useState}from"react";
import{View,Text,StyleSheet,Pressable,ActivityIndicator,Alert,ScrollView}from"react-native";
import{useLocalSearchParams,useRouter}from"expo-router";
import{SafeAreaView}from"react-native-safe-area-context";
import{MaterialCommunityIcons}from"@expo/vector-icons";
import{api}from"@/src/api";

export default function ServicePayment(){
 const r=useRouter(),p=useLocalSearchParams<any>(),plan=p.plan==="full"?"full":"booking",amount=Number(p.amount||0),total=Number(p.total||0);const[method,setMethod]=useState("upi"),[busy,setBusy]=useState(false);
 const pay=async()=>{try{setBusy(true);const out=await api.serviceCartPay({payment_plan:plan,payment_method:method,gateway_reference:""});const id=out?.bookings?.[0]?.id||out?.confirmation_id;r.replace({pathname:"/service-booking-confirmed" as any,params:{id:String(id),confirmation:String(out.confirmation_id),amount:String(out.paid_amount),total:String(out.total_amount),plan}} as any)}catch(e:any){Alert.alert("Payment",""+(e?.message||"Payment could not be completed"))}finally{setBusy(false)}};
 return <SafeAreaView style={s.root}><View style={s.h}><Pressable onPress={()=>r.back()}><MaterialCommunityIcons name="arrow-left" size={24}/></Pressable><Text style={s.t}>Secure Payment</Text></View><ScrollView contentContainerStyle={s.b}>
 <View style={s.hero}><MaterialCommunityIcons name="shield-check" size={42} color="#0284C7"/><Text style={s.heroT}>Pay securely to confirm</Text><Text style={s.meta}>You are paying ₹{amount.toLocaleString("en-IN")} today</Text></View>
 <View style={s.card}><Text style={s.label}>PAYMENT METHOD</Text>{[["upi","UPI","Google Pay · PhonePe · UPI"],["card","Card","Credit / Debit Card"],["netbanking","Net Banking","All major banks"]].map(([id,t,sub])=><Pressable key={id} onPress={()=>setMethod(id)} style={[s.option,method===id&&s.active]}><MaterialCommunityIcons name={id==="upi"?"qrcode-scan":id==="card"?"credit-card-outline":"bank-outline"} size={24} color="#0284C7"/><View style={{flex:1}}><Text style={s.opt}>{t}</Text><Text style={s.meta}>{sub}</Text></View>{method===id&&<MaterialCommunityIcons name="check-circle" size={22} color="#16a34a"/>}</Pressable>)}</View>
 <View style={s.summary}><Text style={s.muted}>Trip total</Text><Text style={s.muted}>₹{total.toLocaleString("en-IN")}</Text><Text style={s.pay}>Pay now</Text><Text style={s.pay}>₹{amount.toLocaleString("en-IN")}</Text></View>
 <Pressable disabled={busy} onPress={pay} style={s.btn}>{busy?<ActivityIndicator color="#fff"/>:<><MaterialCommunityIcons name="lock-check" size={20} color="#fff"/><Text style={s.bt}>Pay ₹{amount.toLocaleString("en-IN")} & Confirm</Text></>}</Pressable>
 <Text style={s.note}>Payment gateway is currently configured as a test flow. Real Razorpay credentials can be connected without changing the checkout design.</Text>
 </ScrollView></SafeAreaView>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:"#f1f7fb"},h:{flexDirection:"row",alignItems:"center",gap:14,padding:16,backgroundColor:"#fff",borderBottomWidth:1,borderColor:"#e2e8f0"},t:{fontSize:21,fontWeight:"900"},b:{padding:16,maxWidth:760,width:"100%",alignSelf:"center",paddingBottom:60},hero:{backgroundColor:"#eaf8ff",borderRadius:22,padding:24,alignItems:"center",marginBottom:14},heroT:{fontSize:20,fontWeight:"900",marginTop:8},meta:{fontSize:12,color:"#64748b",marginTop:4},card:{backgroundColor:"#fff",padding:18,borderRadius:20,borderWidth:1,borderColor:"#e2e8f0",marginBottom:14},label:{fontSize:11,fontWeight:"900",letterSpacing:1.2,color:"#0284C7",marginBottom:9},option:{flexDirection:"row",alignItems:"center",gap:12,padding:14,borderRadius:14,borderWidth:1,borderColor:"#e2e8f0",marginBottom:9},active:{borderColor:"#0284C7",backgroundColor:"#effaff"},opt:{fontWeight:"900",fontSize:15},summary:{backgroundColor:"#fff",borderRadius:16,padding:18,flexDirection:"row",flexWrap:"wrap",justifyContent:"space-between",gap:8},muted:{color:"#64748b"},pay:{fontWeight:"900",fontSize:18},btn:{backgroundColor:"#0284C7",borderRadius:15,padding:16,flexDirection:"row",justifyContent:"center",gap:8,marginTop:14},bt:{color:"#fff",fontWeight:"900",fontSize:16},note:{fontSize:11,color:"#64748b",textAlign:"center",marginTop:12,lineHeight:17}})